
RuhohSpec: '1.0'
theme : twitter

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://username.github.com

# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
posts:
  permalink: /:categories/:title
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
